"""create expense categories and expenses tables

Revision ID: 4e60c3ba57c7
Revises: ad0640a6f010
Create Date: 2026-08-16 23:14:16.564491

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.seed_data import DEFAULT_EXPENSE_CATEGORIES


# revision identifiers, used by Alembic.
revision: str = '4e60c3ba57c7'
down_revision: Union[str, None] = 'ad0640a6f010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_expense_categories_user_id_name')
    )
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=False)
    op.create_index('ix_expense_categories_unique_global_name', 'expense_categories', ['name'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index(op.f('ix_expense_categories_user_id'), 'expense_categories', ['user_id'], unique=False)

    expense_categories = sa.table(
        'expense_categories',
        sa.column('id', sa.Uuid()),
        sa.column('user_id', sa.Uuid()),
        sa.column('name', sa.String()),
    )
    op.bulk_insert(
        expense_categories,
        [
            {'id': uuid.UUID(category.id), 'user_id': None, 'name': category.name}
            for category in DEFAULT_EXPENSE_CATEGORIES
        ],
    )

    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_expense_categories_user_id'), table_name='expense_categories')
    op.drop_index('ix_expense_categories_unique_global_name', table_name='expense_categories', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
